name = "WaterPhysics"
uuid = "20dd5ee6-61da-454b-ac5d-c09c2977e03a"
authors = ["Yujie Wang <jesiner@gmail.com>"]
version = "0.0.1"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
BenchmarkTools = "0.5.0"
julia = "1.0.5"
