name: JuliaStable
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  stable-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: "1.5"
      - run: julia --project -e 'using Pkg; Pkg.test();'
