name: Julia-1.3
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  version-test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Actions
        uses: actions/checkout@v1
      - name: Set up Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: "1.3"
      - name: Test package
        run: julia --project -e 'using Pkg; Pkg.test();'
